version: '3'

services:
  db:
    build: ./db
    container_name: boldr_db
    restart: always
    ports:
      - "5432:5432"
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - boldr

  redis:
    image: redis:3.2.8-alpine
    container_name: boldr_redis
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    user: redis
    networks:
      - boldr

volumes:
  db:
  redis:
  yarn:

networks:
  boldr:
    driver: bridge
