version: '3'

services:
  database:
    build: ./db
    restart: always
    tty: true
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - database_volume:/var/lib/postgresql/data
    healthcheck:
      test: exit 0
    networks:
      - boldr

  redis:
    image: redis:3.2.8-alpine
    volumes:
      - ./internal/docker/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis_volume:/data
    ports:
      - "6379:6379"
    expose:
      - "6379"
    user: redis
    healthcheck:
      test: exit 0
    command:
      "redis-server /usr/local/etc/redis/redis.conf"
    networks:
      - boldr

volumes:
  database_volume: {}
  redis_volume: {}

networks:
  boldr:
    driver: bridge
