version: '2'
services:

  postgres:
    container_name: boldr_pg
    build: ./db
    restart: always
    tty: true
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      # - POSTGRES_DB=boldr
    ports:
      - "5432:5432"
    volumes:
      - pg_volume:/var/lib/postgresql/data
    networks:
      - boldr

  redis:
    image: redis:3.2.6-alpine
    container_name: boldr_redis
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data
    networks:
      - boldr

networks:
  boldr:
    driver: bridge

volumes:
  pg_volume:
    driver: local
  redis_volume:
    driver: local
