// flow-typed signature: ba5180d46eb5ddf5a9fc07ba204b25b8
// flow-typed version: <<STUB>>/apidoc-markdown2_v^0.3.2/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apidoc-markdown2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apidoc-markdown2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'apidoc-markdown2/index' {
  declare module.exports: $Exports<'apidoc-markdown2'>;
}
declare module 'apidoc-markdown2/index.js' {
  declare module.exports: $Exports<'apidoc-markdown2'>;
}
