// flow-typed signature: 744645402d285910f1f018adcbe65739
// flow-typed version: <<STUB>>/objection-softdelete_v^1.0.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'objection-softdelete'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'objection-softdelete' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'objection-softdelete/test/_knexfile' {
  declare module.exports: any;
}

declare module 'objection-softdelete/test/_prepare-test-db' {
  declare module.exports: any;
}

declare module 'objection-softdelete/test/force-delete' {
  declare module.exports: any;
}

declare module 'objection-softdelete/test/helpers/models' {
  declare module.exports: any;
}

declare module 'objection-softdelete/test/helpers/objection' {
  declare module.exports: any;
}

declare module 'objection-softdelete/test/include-deleted' {
  declare module.exports: any;
}

declare module 'objection-softdelete/test/many-to-many' {
  declare module.exports: any;
}

declare module 'objection-softdelete/test/override-delete' {
  declare module.exports: any;
}

declare module 'objection-softdelete/test/skip-deleted-on-fetch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'objection-softdelete/index' {
  declare module.exports: $Exports<'objection-softdelete'>;
}
declare module 'objection-softdelete/index.js' {
  declare module.exports: $Exports<'objection-softdelete'>;
}
declare module 'objection-softdelete/test/_knexfile.js' {
  declare module.exports: $Exports<'objection-softdelete/test/_knexfile'>;
}
declare module 'objection-softdelete/test/_prepare-test-db.js' {
  declare module.exports: $Exports<'objection-softdelete/test/_prepare-test-db'>;
}
declare module 'objection-softdelete/test/force-delete.js' {
  declare module.exports: $Exports<'objection-softdelete/test/force-delete'>;
}
declare module 'objection-softdelete/test/helpers/models.js' {
  declare module.exports: $Exports<'objection-softdelete/test/helpers/models'>;
}
declare module 'objection-softdelete/test/helpers/objection.js' {
  declare module.exports: $Exports<'objection-softdelete/test/helpers/objection'>;
}
declare module 'objection-softdelete/test/include-deleted.js' {
  declare module.exports: $Exports<'objection-softdelete/test/include-deleted'>;
}
declare module 'objection-softdelete/test/many-to-many.js' {
  declare module.exports: $Exports<'objection-softdelete/test/many-to-many'>;
}
declare module 'objection-softdelete/test/override-delete.js' {
  declare module.exports: $Exports<'objection-softdelete/test/override-delete'>;
}
declare module 'objection-softdelete/test/skip-deleted-on-fetch.js' {
  declare module.exports: $Exports<'objection-softdelete/test/skip-deleted-on-fetch'>;
}
