version: '3'

services:
  api:
    build: .
    container_name: boldr_api

    environment:
      - BOLDR__DB__URL=postgres://postgres:password@database:5432/boldr
      - BOLDR__REDIS__URL=redis://redis:6379/0
    expose:
      - "2121"
    ports:
      - "2121:2121"
    volumes:
      - yarn:/root/.cache/yarn
      - /app/node_modules
      - ./:/app
      - "./static:/app/static"
      - "./logs:/app/logs"
    user: node
    command: yarn start
    working_dir: /app
    links:
      - database
      - redis
    networks:
      - boldr


  database:
    build: ./db
    restart: always
    tty: true
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - database_volume:/var/lib/postgresql/data
    healthcheck:
      test: exit 0
    networks:
      - boldr

  redis:
    image: redis:3.2.8-alpine
    volumes:
      - redis_volume:/data
    expose:
      - "6379"
    ports:
      - "6379:6379"
    user: redis
    healthcheck:
      test: exit 0
    networks:
      - boldr


volumes:
  database_volume: {}
  redis_volume: {}
  yarn: {}

networks:
  boldr:
    driver: bridge
