version: '3'

services:

  api:
    build: .
    container_name: boldr_api
    depends_on:
      - db
      - redis
    environment:
      - NODE_DEBUG=false
      - DATABASE_DEBUG=false
      - DATABASE_URI=postgres://postgres:password@127.0.0.1:5432/boldr
      - REDIS_URI=redis://127.0.0.1:6379/0
      - TOKEN_SECRET=b0ldr@p1k3k
    expose:
      - "2121:2121"
    ports:
      # V8 inspector (when NODE_DEBUG=true)
      - "127.0.0.1:9229:9229"
    volumes:
      - yarn:/root/.cache/yarn
      - ./:/app
      - "./static:/app/static"
    user: node
    working_dir: /app
    networks:
      - boldr
    command: yarn start

  db:
    build: ./db
    container_name: boldr_db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - boldr

  redis:
    image: redis:3.2.8-alpine
    container_name: boldr_redis
    env_file: .env
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    user: redis
    networks:
      - boldr

volumes:
  db:
  redis:
  yarn:

networks:
  boldr:
    driver: bridge
